title: <p align="center"> Rajdeep Karpe </p>

logo: "/images/LinkedIn1.png?raw=true"

description:
  <p align="center">
  <a href="pdf/Rajdeep_Data_Science_Res.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/rajdeepkarpe/">LinkedIn</a> |
  <a href="https://github.com/RajdeepKarpe22">GitHub</a>
  </p>
  
  <p align="justify">
  I have completed MS degree in Data Analytics at National College of Ireland in Dublin, Ireland.
  <br><br>
  I am currently a Data Scientist Intern at Orcawise ltd. with a focus on Natural Language Processing.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-202576275-1 # Google Analytics tracking ID
